#!/bin/bash
set -eu -o pipefail
trap 'echo "Failed pre-commit hook"' ERR

if ! git remote -v | grep -q 'spinalcordtoolbox'; then
    echo "This repository is not linked to an upstream named 'spinalcordtoolbox'. Skipping pre-commit hook."
    exit 0
fi

echo "PRE-COMMIT HOOK RAN"
git diff --name-only --diff-filter=d --cached |\
    (grep '\.py$' || (($? < 2)) ) |\
    xargs --delimiter='\n' --no-run-if-empty flake8
